name: "Test and verify Terraform code"
description: "Combining all test actions into one"
runs:
  using: "composite"
  
  steps:
    - uses: hashicorp/setup-terraform@v2
    - name: Terraform Validate
      run: terraform validate
      shell: bash
      working-directory: terraform
    - name: Terraform fmt
      run: terraform fmt -check
      shell: bash
      working-directory: terraform
      continue-on-error: false
    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v3
      with:
        tflint_version: v0.48.0
    - name: Terraform lint
      run: tflint -f compact
      shell: bash
      working-directory: terraform

